--- 
- name: install tomcat 
  become: yes 
  hosts: appserver 
  vars: 
    java_version: 11
    username: tomcat
    groupname: tomcat
    homedir: /opt/tomcat
    shell: /bin/false   
    tomcat_major_version: 10
    tomcat_specific_version: 10.1.14
    download_url: 
  tasks: 
   - name: install openjdk  
     ansible.builtin.apt: 
       name: "openjdk-{{ java_version }}-jdk"  
       update_cache: yes   
       state: present 
   - name: creating group for tomcat
     ansible.builtin.group: 
       name: "{{ groupname }}"
       state: present 
   - name: creating user as tomcat
     ansible.builtin.user: 
       name: "{{ username }}"
       group: "{{ groupname }}"
       home: "{{ homedir }}"
       shell: "{{ shell }}"
       state: present  
   - name: download and extract tomcat
     ansible.builtin.unarchive: 
       src:  "https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_specific_version }}/bin/apache-tomcat-{{ tomcat_specific_version }}.tar.gz"
       copy: true  
       creates: "{{ homedir }}/apache-tomcat-{{ tomcat_specific_version }}" 
       dest: "{{ homedir }}"
       group: "{{ groupname }}"
       owner: "{{ username }}"
   - name: create symbolic link 
     ansible.builtin.file: 
       src: "{{ homedir }}/apache-tomcat-{{ tomcat_specific_version }}"
       dest: "{{ homedir }}/latest"
       owner: "{{ username }}"
       group: "{{ groupname }}"
       state: link
   - name: Recursively chnages ownership of a directory 
     ansible.builtin.file: 
       path: "{{ homedir }}"
       state: directory
       recurse: true 
       owner: "{{ username }}"
       group: "{{ groupname }}" 
   - name: Give execute permission to Shell 
     ansible.builtin.command: 
       

     





