---
- name: install mysql srever
  become: yes 
  hosts: dbserver 
  tasks: 
    - name: install mysql 
      ansible.builtin.apt:
        name: mysql-server
        update_cache: true  
        state: yes   
        

